### ISSUE TITLE
Sourcing nvm-wrapper doesn't work on OS X

### ISSUE THREAD

**Issue by taktran** [passcod/nvm-fish-wrapper#8] opened 2015-03-07 16:59 UTC
I tried putting this in my `~/.config/fish/config.fish`:

```
source ~/.config/fish/nvm-wrapper/nvm.fish
```

But when I start a new terminal I get

```
N/A: version "default" is not yet installed
```

Also, when I do `nvm --version`, I get

```
/var/folders/38/yjtncyws5617fdmj7xkp41yc0000gn/T/nvm-wrapper.7S63h74P/oldenv: line 1: 15:PATH=/usr/local/Cellar/coreutils/8.23_1/libexec/gnubin:/usr/local/share/npm/bin:/Users/[user]/bin/AWS-ElasticBeanstalk-CLI-2.6.3/eb/macosx/python2.7/:/Users/[user]/Library/Android/sdk/tools:/Users/[user]/Library/Android/sdk/platform-tools:/Users/[user]/.rbenv/shims:/Users/[user]/.rbenv/bin:/usr/local/bin:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin: No such file or directory
```

Did I do something stupid with my `PATH`?

`nvm` does work when I use `bash` though.

**Comment by passcod** [comment] 2015-03-08 10:47
Sigh. I need to put up a big warning: **_"Not tested with OS X"**_

I can't debug your issue, I don't have a Mac. If you find a fix, please please submit a PR or send me a diff or patch, and I'll test it on Linux and see what can be done. Sorry I can't be more helpful.

**Comment by passcod** [comment] 2015-03-08 10:56
May be related to #7

**Comment by jkarttunen** [comment] 2015-04-12 06:32
@taktran  have you tried setting the default node version with nvm?

**Comment by taktran** [comment] 2015-04-12 15:30
@jkarttunen I can't set a default node version because, none of the `nvm` commands work when I'm in fishfish

Is #7 solved @passcod ?

**Comment by passcod** [comment] 2015-04-19 10:17
@taktran Nope. Your best bet is to drop into bash, source nvm, install a node and set the default, and try again, see if it works.

**Comment by holyjak** [comment] 2015-04-19 22:01
@taktran I have the same problem with "N/A: version "default" is not yet installed" though no path issue  (on quite a fresh Yosemite 10.10.3, nvm installed via brew).

```
$ . nvm-wrapper/nvm.fish
N/A: version "default" is not yet installed
$ nvm alias default v0.10
! WARNING: Version 'v0.10' does not exist.
default -> v0.10 (-> N/A)
$ nvm install v0.10
N/A: version "v0.10" is not yet installed  # huh?!
$  nvm ls
N/A: version "v0.10" is not yet installed
```

So something is, excuse me, fishy here. I need to investigate more.

_UPDATE_ There is clearly some conflict between fish and bash nvm/variables (I've orignally used the bash nvm to install a node version). When I start bash _from fish_, i.e. inheriting some fish env variables:

```
fish$ bash
bash-3.2$ nvm ls
bash: nvm: command not found
bash-3.2$ source /usr/local/opt/nvm/nvm.sh
N/A: version "v0.10" is not yet installed               # <-- notice the same error
bash-3.2$ nvm ls

->       system
default -> v0.10 (-> N/A)
node -> stable (-> N/A) (default)
iojs -> iojs- (-> N/A) (default)
bash-3.2$ nvm install v0.10
v0.10.38 is already installed.
Now using node v0.10.38
```

However when I start a fresh bash as a login shell, not from fish, nvm works there flawlessly.

Here are some important differences:

```
login bash$ env | grep NVM
NVM_PATH=/Users/me/.nvm/v0.10.38/lib/node
NVM_DIR=/Users/me/.nvm
NVM_BIN=/Users/me/.nvm/v0.10.38/bin

bash from fish after sourcing nvm.sh there$ env | grep NVM
NVM_PATH=/usr/local/opt/nvm/v0.10.38/lib/node
NVMSH=/usr/local/opt/nvm/nvm.sh
NVM_DIR=/usr/local/opt/nvm
NVM_BIN=/usr/local/opt/nvm/v0.10.38/bin
```

See the difference `~/.nvm` versus `/usr/local/opt/nvm`? That is our hint.

Good night and hopefully I find out more tomorrow.

**Comment by holyjak** [comment] 2015-04-19 22:12
Uh, sorry, ignore the env var differences - that was due to me trying to help nvm.fish find nvm.sh by adding this:

```
if test -f (brew --prefix nvm)/nvm.sh
   set -x NVMSH (brew --prefix nvm)/nvm.sh
else
  set -x NVMSH ~/.nvm/nvm.sh
end
```

**Comment by passcod** [comment] 2015-04-19 22:49
Still, great work there @jakubholynet — hopefully you'll find additional hints pointing to an eventual solution!

**Comment by holyjak** [comment] 2015-04-20 06:25
Update:

```
fish$ env | egrep 'nvm|NVM'
fish$ bash -c "source /usr/local/opt/nvm/nvm.sh"
N/A: version "v0.10" is not yet installed
fish$ bash -lc "source /usr/local/opt/nvm/nvm.sh"
fish$
```

So I do not have any NVM variables set but sourcing nvm.sh from bash still fails. But if I source it as a login shell, it succeeds. (Sourcing from within bash, i.e. `bash$ bash -c "source /usr/local/opt/nvm/nvm.sh"` works correctly as well.) So there is something fishy about fish but I do not know what (BTW have not sourced nvm.fish in the fish shell I have used above.)

It looks like nvm.sh remembers correctly that I have aliased v0.10 as my default but somehow cannot find it when run from fish. Perhaps it looks at a different path?!

Any further troubleshooting ideas?

_\UPDATE_: The difference with `-l` is that nvm.sh is sourced once - and presumably the first sourcing sets things up right so the next one (the only one run when exec without -l) does not fail.

When I add some logging to nvm.sh:

```
fish$ bash -lc "source /usr/local/opt/nvm/nvm.sh"; cat /tmp/log
nvm_alias(default): looking at alias path /Users/me/.nvm/alias/default
fish$ bash -c "source /usr/local/opt/nvm/nvm.sh"; cat /tmp/log
N/A: version "v0.10" is not yet installed
nvm_alias(v0.10): looking at alias path /usr/local/opt/nvm/alias/v0.10
```

So the bash-only nvm looks at aliases in `~/.nvm/alias/` while under fish it looks into `/usr/local/opt/nvm/alias/` (and there is no v0.10 in any of the two)

**Comment by holyjak** [comment] 2015-04-20 06:46
**FIXED**: By adding `set -x  NVM_DIR ~/.nvm` prior to sourcing `nvm.fish`, I got rid of the error.

The problem is that nvm tries to guess its dir from the location of the nvm.sh script, which does not work as expected when the script is under brew. When nvm.sh was installed, brew has recommended to put both setting NVM_DIR and sourcing nvm into ~/.profile.

**Comment by passcod** [comment] 2015-04-20 09:13
I'll add this to the README. @taktran Can you try this and report back?

**Comment by taktran** [comment] 2015-04-20 17:59
Nope, I tried

```
$ set -x NVM_DIR ~/.nvm
$ source ~/.config/fish/nvm-wrapper/nvm.fish
/var/folders/38/yjtncyws5617fdmj7xkp41yc0000gn/T/nvm-wrapper.WkIEOqMO/oldenv: line 1: 17:NVM_DIR=/Users/ttt/.nvm: No such file or directory
/var/folders/38/yjtncyws5617fdmj7xkp41yc0000gn/T/nvm-wrapper.WkIEOqMO/oldenv: line 2: 18:PATH=/usr/local/Cellar/coreutils/8.23_1/libexec/gnubin:/usr/local/share/npm/bin:/Users/ttt/bin/AWS-ElasticBeanstalk-CLI-2.6.3/eb/macosx/python2.7/:/Users/ttt/Library/Android/sdk/tools:/Users/ttt/Library/Android/sdk/platform-tools:/Users/ttt/.rbenv/shims:/Users/ttt/.rbenv/bin:/usr/local/bin:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin: No such file or directory
```

Are there files outside of `~/.config/fish/nvm-wrapper` that I need to clear?

**Comment by holyjak** [comment] 2015-04-20 19:46
What if you run nvm.sh from bash (that you haven't started from fish)? Does
nvm work there? What directories is it using?

## 

Forget software. Strive to make an impact, deliver a valuable change.

(Vær så snill og hjelp meg med å forbedre norsken min – skriftlig og
muntlig. Takk!)

Jakub Holy
Solutions Engineer | +47 966 23 666
Iterate AS | www.iterate.no
The Lean Software Development Consultancy
- http://theholyjava.wordpress.com/ -
- apr. 2015 19:59 skrev "Tak Tran" notifications@github.com:

**Comment by passcod** [comment] 2015-04-20 21:50
`/tmp/folder/somewhere/oldenv` is something used within the wrapper. Given the error you're getting, for some reason sourcing that from bash isn't working on your system. That may have to do with the `17:...` and `18:...` that look like are prepended. When you get this error, try to `cat` the `oldenv` file, see what it looks like (and paste it here)? If that doesn't work, open up `nvm.fish` and comment out line 100, `rm -r $tmpdir`, then try again… the temporary env files should remain now, which should let you investigate.

**Comment by doughsay** [comment] 2015-04-30 23:13
FWIW: I don't know if things have changed in the past 10 days but I ran into no problems.  Here's what I did (fresh install, reproducible):

```
$ git clone https://github.com/creationix/nvm.git ~/.nvm
Cloning into '/Users/chris/.nvm'...
remote: Counting objects: 3610, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 3610 (delta 3), reused 0 (delta 0), pack-reused 3602
Receiving objects: 100% (3610/3610), 772.66 KiB | 264.00 KiB/s, done.
Resolving deltas: 100% (2072/2072), done.
Checking connectivity... done.
$ cd ~/.nvm
$ git checkout (git describe --abbrev=0 --tags)                                                                        node none
Note: checking out 'v0.25.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at eb5cecc... v0.25.0
```

Then in a new terminal:

```
Last login: Thu Apr 30 16:03:38 on ttys001
N/A: version "default" is not yet installed
$ nvm install iojs-v1.8.1
######################################################################## 100.0%
WARNING: checksums are currently disabled for io.js
Now using io.js v1.8.1 (npm v2.8.3)
$ nvm alias default iojs-v1.8.1
default -> iojs-v1.8.1
```

Everything works after this, new terminal have the right version set and everything.

`set -x NVM_DIR ~/.nvm` is not needed in config.fish

And also, (RE: https://github.com/passcod/nvm-fish-wrapper/issues/7):

```
$ man git > /dev/null; and echo "success"
success
$ man iojs > /dev/null; and echo "success"
success
```

**Comment by passcod** [comment] 2015-05-01 00:00
@doughsay Right, this issue is only relevant if you use Homebrew and/or use Homebrew to install nvm. I'll modify the README to precise that it works using git to install nvm.

**Comment by doughsay** [comment] 2015-05-01 00:59
@passcod sounds good, and thanks for creating this!  Super helpful!

**Comment by passcod** [comment] 2015-09-26 02:00
Closing down (see Readme).

**Closed as completed by passcod** 2015-09-26 02:00 UTC
Labels: bug, help wanted, OS X
